generate:
	./tree-sitter generate

setup:
	npm install
	ln -s node_modules/.bin/tree-sitter tree-sitter

clean:
	rm -rf node_modules
	rm -rf bindings
	rm -rf src
	rm -f binding.gyp Cargo.toml tree-sitter
