rel eval(e, c) :- constant(e, c)
rel eval(e, a + b) :- binary(e, "+", l, r), eval(l, a), eval(r, b)
rel eval(e, a * b) :- binary(e, "*", l, r), eval(l, a), eval(r, b)
rel eval(e, a / b) :- binary(e, "/", l, r), eval(l, a), eval(r, b)
rel eval(e, -a) :- unary(e, "-", o), eval(o, a)

rel constant :- {
  0.2::(0, 1),
  0.5::(0, 2),
  0.2::(0, 3),
  0.1::(0, 4),

  0.1::(1, 1),
  0.7::(1, 2),
  0.1::(1, 3),
  0.1::(1, 4),
}

rel binary :- {
  0.9::(2, "+", 0, 1),
  0.1::(2, "-", 0, 1),
}
