// P1: Tom and Jerry are playing soccer.
// P2: 11 people are playing soccer.
// Q: How many people are playing?

rel verb = {
  (1, "play"),
  (4, "play"),
}

rel noun = {
  (2, "Tom", "Person"),
  (3, "Jerry", "Person")
}

rel arg1 = {
  (1, 2),
  (1, 3),
}

rel synonym = {
  (1, 4),
}

rel plays_soccer(n) =
  verb(vid0, "play"),
  arg1(vid, n),
  noun(n, _, "Person"),
  synonym(vid, vid0)

rel how_many_play_soccer(c) = c = count(n: plays_soccer(n))
