rel eval(e, c) :- constant(e, c)
rel eval(e, a + b) :- binary(e, "+", l, r), eval(l, a), eval(r, b)
rel eval(e, a * b) :- binary(e, "*", l, r), eval(l, a), eval(r, b)
rel eval(e, a / b) :- binary(e, "/", l, r), eval(l, a), eval(r, b)
rel eval(e, -a) :- unary(e, "-", o), eval(o, a)
rel result(y) :- eval(e, y), goal(e)

rel constant :- {
  (0, 1),
  (1, 2),
}

rel binary :- {
  (2, "+", 0, 1)
}

rel goal(2)

query result
