import "scene_graph.scl"

rel obj_color = {
  (0, "yellow"),
  (1, "red"),
  (2, "green"),
  (3, "blue"),
  (4, "blue"),
  (5, "red"),
}

rel obj_shape = {
  (0, "cube"),
  (1, "sphere"),
  (2, "cube"),
  (3, "cylinder"),
  (4, "cube"),
  (5, "cylinder"),
}

rel left = {
  (0, 1), (0, 2), (0, 3), (0, 4), (0, 5),
  (1, 2), (1, 3), (1, 4), (1, 5),
  (2, 3), (2, 4), (2, 5),
  (3, 4), (3, 5),
  (4, 5),
}
